/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudEnrollmentMini;

import HELRER.Comp;
import HELRER.Functions;
import Panel.Panel_Course;
import Panel.Panel_Enrollment;
import Panel.Panel_Reports;
import Panel.Panel_Student;
import Panel.Panel_Subject;
import Panel.Panel_Teacher;
import Panel.Panel_dashboard;
import Panel.Panel_lecture;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainGui() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l_image = new javax.swing.JLabel();
        l_name = new javax.swing.JLabel();
        l_position = new javax.swing.JLabel();
        l_enrollment = new javax.swing.JLabel();
        l_dashboard = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        l_teacher = new javax.swing.JLabel();
        l_course = new javax.swing.JLabel();
        l_subject = new javax.swing.JLabel();
        l_student = new javax.swing.JLabel();
        l_logout = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l_lecture = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EnCoderPro: Course Enrollment");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(28, 126, 231));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        l_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/ava3_120x133.png"))); // NOI18N

        l_name.setForeground(new java.awt.Color(255, 255, 255));
        l_name.setText("Name: ???????????????");

        l_position.setForeground(new java.awt.Color(255, 255, 255));
        l_position.setText("Position: ??????????????????");

        l_enrollment.setBackground(new java.awt.Color(28, 126, 231));
        l_enrollment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_enrollment.setForeground(new java.awt.Color(255, 255, 255));
        l_enrollment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/enrollment.png"))); // NOI18N
        l_enrollment.setText("  Enrollment");
        l_enrollment.setOpaque(true);

        l_dashboard.setBackground(new java.awt.Color(28, 126, 231));
        l_dashboard.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_dashboard.setForeground(new java.awt.Color(255, 255, 51));
        l_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/dashboard.png"))); // NOI18N
        l_dashboard.setText("  Dashboard");
        l_dashboard.setOpaque(true);
        l_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_dashboardMouseClicked(evt);
            }
        });

        l_teacher.setBackground(new java.awt.Color(28, 126, 231));
        l_teacher.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_teacher.setForeground(new java.awt.Color(255, 255, 255));
        l_teacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/teacher.png"))); // NOI18N
        l_teacher.setText("  Teacher");
        l_teacher.setOpaque(true);

        l_course.setBackground(new java.awt.Color(28, 126, 231));
        l_course.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_course.setForeground(new java.awt.Color(255, 255, 255));
        l_course.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/bookshelf.png"))); // NOI18N
        l_course.setText("  Course");
        l_course.setOpaque(true);

        l_subject.setBackground(new java.awt.Color(28, 126, 231));
        l_subject.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_subject.setForeground(new java.awt.Color(255, 255, 255));
        l_subject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/book.png"))); // NOI18N
        l_subject.setText("  Subject");
        l_subject.setOpaque(true);

        l_student.setBackground(new java.awt.Color(28, 126, 231));
        l_student.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_student.setForeground(new java.awt.Color(255, 255, 255));
        l_student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/student1.png"))); // NOI18N
        l_student.setText("  Student");
        l_student.setOpaque(true);

        l_logout.setBackground(new java.awt.Color(28, 126, 231));
        l_logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_logout.setForeground(new java.awt.Color(255, 255, 255));
        l_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/logout.png"))); // NOI18N
        l_logout.setText("Exit");
        l_logout.setOpaque(true);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(java.awt.Color.darkGray);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/cc2.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Asay Academy");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Menu");

        l_lecture.setBackground(new java.awt.Color(28, 126, 231));
        l_lecture.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_lecture.setForeground(new java.awt.Color(102, 102, 102));
        l_lecture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_lecture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/training.png"))); // NOI18N
        l_lecture.setToolTipText("Assign Lecture");
        l_lecture.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        l_lecture.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_position, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(l_teacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_course, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_enrollment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_student, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l_subject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_lecture, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_image, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_position)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_enrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_student, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_lecture, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_course, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        MainPanel.setBackground(new java.awt.Color(255, 239, 239));
        MainPanel.setPreferredSize(new java.awt.Dimension(887, 585));
        MainPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MainPanelKeyPressed(evt);
            }
        });
        MainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_dashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l_dashboardMouseClicked

    private void MainPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MainPanelKeyPressed
        //
    }//GEN-LAST:event_MainPanelKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_course;
    private javax.swing.JLabel l_dashboard;
    private javax.swing.JLabel l_enrollment;
    private javax.swing.JLabel l_image;
    private javax.swing.JLabel l_lecture;
    private javax.swing.JLabel l_logout;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel l_position;
    private javax.swing.JLabel l_student;
    private javax.swing.JLabel l_subject;
    private javax.swing.JLabel l_teacher;
    // End of variables declaration//GEN-END:variables

    Functions functions;
    Comp comp;

//Declaraction of class, components and variables
    Panel_dashboard dashboardPanel;
    Panel_Enrollment enrollmentPanel;
    Panel_Reports reportPanel;
    Panel_Student studentPanel;
    Panel_Teacher teacherPanel;
    Panel_Subject subjectPanel;
    Panel_Course coursePanel;
    Panel_lecture lecturePanel;

//    Initialize ocmponents and variables
    private void init() {

        //
        functions = new Functions();
        comp = new Comp();
        //
        callAllPanels();//load all panels
        //Set DashboardPanel Default

        //
        comp.frameIcon(this);
        Comp.centerJFrame(this);
        //mouse clicked function
        mouseClickedOnLabel();

    }

    //load all panels
    private void callAllPanels() {//Start
        dashboardPanel = new Panel_dashboard();//0
        enrollmentPanel = new Panel_Enrollment();//1  
        studentPanel = new Panel_Student();//2
        teacherPanel = new Panel_Teacher();//3
        subjectPanel = new Panel_Subject();//4
        coursePanel = new Panel_Course();//5
        reportPanel = new Panel_Reports();//6
        lecturePanel = new Panel_lecture();//7

    }//End

    private void loadPanel(JLabel labe) {

        String message = labe.getText();
        String newMessage = "";
        if (message.equals("")) {
            if (labe.getToolTipText().equals("Assign Lecture")) {
                newMessage = "Lecture";
            }
        } else {
            newMessage = message;
        }

        switch (newMessage) {

            case "  Dashboard":

                dashboardPanel.setUserId(_id);
                dashboardPanel.setSchoolYear(schoolYear);
                dashboardPanel.setSemester(yearSemester);
                dashboardPanel.getDataToAccess();
                Comp.refreshPanel(MainPanel, dashboardPanel);
                labe.setForeground(new java.awt.Color(255, 255, 51));

                break;
            case "  Enrollment":
                enrollmentPanel.setUserId(_id);
                enrollmentPanel.setSemester(yearSemester);
                enrollmentPanel.setYearInclusive(schoolYear);
                enrollmentPanel.getYearSemesterData();
                Comp.refreshPanel(MainPanel, enrollmentPanel);
                labe.setForeground(new java.awt.Color(255, 255, 51));

                break;
            case "  Student":

                studentPanel.setUserId(_id);
                studentPanel.setYearInclusive(schoolYear);
                studentPanel.loadUserCredentials();
                Comp.refreshPanel(MainPanel, studentPanel);
                labe.setForeground(new java.awt.Color(255, 255, 51));

                break;
            case "  Teacher":

                teacherPanel.setUserID(_id);
                teacherPanel.setSchoolYear(schoolYear);
                teacherPanel.setSemester(yearSemester);
                teacherPanel.loadUserCredentials();
                Comp.refreshPanel(MainPanel, teacherPanel);
                labe.setForeground(new java.awt.Color(255, 255, 51));

                break;
            case "  Subject":

                subjectPanel.setUserId(_id);
                subjectPanel.setSchoolYear(schoolYear);
                subjectPanel.setSemester(yearSemester);
                subjectPanel.loadUserCredentials();
                Comp.refreshPanel(MainPanel, subjectPanel);
                labe.setForeground(new java.awt.Color(255, 255, 51));

                break;
            case "  Course":

                coursePanel.setUserId(_id);
                coursePanel.setSchoolYear(schoolYear);
                coursePanel.setSemester(yearSemester);
                coursePanel.loadUserCredentials();
                Comp.refreshPanel(MainPanel, coursePanel);
                labe.setForeground(new java.awt.Color(255, 255, 51));

                break;
            case "  Reports":
                Comp.refreshPanel(MainPanel, reportPanel);
                labe.setForeground(new java.awt.Color(255, 255, 51));

                break;
            case "Lecture":

                lecturePanel.setUserId(_id);
                lecturePanel.loadUserCredentials();
                Comp.refreshPanel(MainPanel, lecturePanel);
                labe.setBackground(new java.awt.Color(255, 255, 255));
                break;
        }
    }//end

    //do action when clicking the label
    private void mouseClickedOnLabel() {//Start

        l_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetLabels();
                loadPanel(l_dashboard);
            }
        });
        l_enrollment.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetLabels();
                loadPanel(l_enrollment);
            }
        });
        l_student.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetLabels();
                loadPanel(l_student);
            }
        });
        l_teacher.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetLabels();
                loadPanel(l_teacher);
            }
        });
        l_subject.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetLabels();
                loadPanel(l_subject);
            }
        });
        l_course.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetLabels();
                loadPanel(l_course);
            }
        });
//        l_reports.addMouseListener(new java.awt.event.MouseAdapter() {
//            @Override
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                resetLabels();
//                loadPanel(l_reports);
//            }
//        });
        l_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                System.exit(0);
            }
        });

        l_lecture.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetLabels();
                loadPanel(l_lecture);
            }
        });

    }//End

    //Resel all labels
    private void resetLabels() {
        l_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        l_enrollment.setForeground(new java.awt.Color(255, 255, 255));
        l_student.setForeground(new java.awt.Color(255, 255, 255));
        l_teacher.setForeground(new java.awt.Color(255, 255, 255));
//        l_reports.setForeground(new java.awt.Color(255, 255, 255));
        l_subject.setForeground(new java.awt.Color(255, 255, 255));
        l_course.setForeground(new java.awt.Color(255, 255, 255));
        //
        l_lecture.setBackground(new java.awt.Color(28, 126, 231));
    }

    //
    // USER ==========================
    //
    /*get data from login*/
    public void getAndLoadUserInfo() {//Start function
        _id = getId();
        _Name = getName();
        _Position = getPosition();
        _image = getImage();
        l_name.setText("Name: " + _Name);
        l_position.setText("Position: " + _Position);
//        functions._imageProperties(Functions._DIR_ + "" + _image, 140, 130, l_image);
        schoolYear = getYearInclusive();
        yearSemester = getYearSemester();
//        /
        dashboardPanel.setUserId(_id);
        dashboardPanel.setSchoolYear(schoolYear);
        dashboardPanel.setSemester(yearSemester);
        dashboardPanel.getDataToAccess();
        Comp.refreshPanel(MainPanel, dashboardPanel);

    }//End function

    private byte _id;
    private String _Name, _Position, _image;

    public byte getId() {
        return _id;
    }

    public void setId(byte _id) {
        this._id = _id;
    }

    public String getName() {
        return _Name;
    }

    public void setName(String _Name) {
        this._Name = _Name;
    }

    public String getPosition() {
        return _Position;
    }

    public void setPosition(String _Position) {
        this._Position = _Position;
    }

    public String getImage() {
        return _image;
    }

    public void setImage(String _image) {
        this._image = _image;
    }

    //
    // USER ==========================
    //
    private String schoolYear, yearSemester;

    public String getYearInclusive() {
        return schoolYear;
    }

    public void setYearInclusive(String yearInclusive) {
        this.schoolYear = yearInclusive;
    }

    public String getYearSemester() {
        return yearSemester;
    }

    public void setYearSemester(String yearSemester) {
        this.yearSemester = yearSemester;
    }
}
